### ISSUE TITLE
Typo on 070.js

### ISSUE THREAD

**Issue by lvaldovinos** [sporto/planetproto#20]
Hi there,

I think there's a typo here:

// -> Define an object called 'Robot'
// -> Define a method called 'new' in Robot
// -> When Robot.new is called ~~is~~  it should return a new object with Robot as its prototype 
//    e.g. var robby = Robot.new();
//    Robot should be the prototype of robby

Regards.
Btw. thanks for this workshop, finally understood how prototypes work on javascript.

**Comment by sporto** [comment]
Thanks, fixed
